version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
<<<<<<< HEAD
stack_name = "todo-list-aws"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-93ltpaas6fx" #Incluir bucket propio
s3_prefix = "todo-list-aws"
=======
stack_name = "todo-list-aws-production"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-93ltpaas6fx" #Incluir bucket propio
s3_prefix = "todo-list-aws-production"
>>>>>>> origin/master
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"production\""
image_repositories = []
confirm_changeset = true

[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "todo-list-aws-staging"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-93ltpaas6fx" #Incluir bucket propio
s3_prefix = "todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"staging\""
image_repositories = []

[production]
[production.deploy]
[production.deploy.parameters]
stack_name = "todo-list-aws-production"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-93ltpaas6fx" #Incluir bucket propio
s3_prefix = "todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"production\""
image_repositories = []
